common: &common
  build: .
  working_dir: /go/src/github.com/stevenjack/cig

dev:
  <<: *common
  command: go run cig.go --cp /go/src/github.com/stevenjack/cig
  volumes:
    - .:/go/src/github.com/stevenjack/cig
    - ~/Projects:/projects

build:
  <<: *common
  command: gox
  volumes:
    - .:/go/src/github.com/stevenjack/cig
